openapi: 3.1.0

info:
  title: API de Localização
  version: 1.0.0
servers:
  - url: https://apidelocalizacao.vercel.app
tags:
  - name: Localização

paths:
  /cities:
    get:
      summary: Listar cidades
      operationId: cities/list
      tags:
        - Localização
      parameters:
        - name: name
          in: query
          description: O nome da cidade para busca
          required: false
          schema:
            type: string
        - name: page
          in: query
          description: O número da página
          required: false
          schema:
            type: integer
            default: 1
        - name: perPage
          in: query
          description: O número de cidades por página
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Cidades encontradas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
        '400':
          description: Erro de validação
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '5XX':
          description: Erro inesperado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

  /cities/distances:
    get:
      summary: Obter distância entre cidades
      operationId: cities/distances/get
      tags:
        - Localização
      parameters:
        - name: originCityId
          in: query
          description: O identificador da cidade de origem
          required: true
          schema:
            type: integer
          example: 1
        - name: destinationCityId
          in: query
          description: O identificador da cidade de destino
          required: true
          schema:
            type: integer
          example: 2
      responses:
        '200':
          description: Distância encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Distance'
        '400':
          description: Erro de validação
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '404':
          description: Uma ou ambas as cidades não encontradas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        '5XX':
          description: Erro inesperado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

components:
  schemas:
    City:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          description: O identificador da cidade
          example: 1
        name:
          type: string
          description: O nome da cidade
          example: São Paulo
        state:
          type: object
          description: O estado da cidade
          properties:
            id:
              type: integer
              description: O identificador do estado
              example: 2
            name:
              type: string
              description: O nome do estado
              example: São Paulo
            country:
              type: string
              description: O país do estado
              example: Brasil

    Distance:
      type: object
      required:
        - distance
      properties:
        distance:
          type: number
          description: A distância em quilômetros (km)
          format: double
          example: 145.3

    ValidationError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: A mensagem de erro
          example: Entrada inválida

    NotFoundError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: A mensagem de erro
          example: Item não encontrado

    InternalServerError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: A mensagem de erro
          example: Erro inesperado
